// Project data — single source of truth.
// 임팩트순으로 정렬됨. 사용자가 나중에 순서 조정 가능.
const PROJECTS = [
  {
    id: "01",
    name: "Hive Survivor",
    tagline: "장비 뽑기와 강화로 빌드를 만드는 2D 뱀서라이크",
    genre: "2D 탑다운 / 뱀서라이크",
    duration: "2025.02.24 ~ 2025.03.10\n(14일)",
    period: "2025",
    team: "1인 (단독 개발)",
    role: "클라이언트",
    engine: "Unity 2022.3.16f1 LTS\nVisual Studio 2019\nGitHub Desktop",
    platform: "PC",
    intent: "이 프로젝트의 목표는 플레이어가 여러 층위에서 \"내 빌드를 만들어 가는 재미\"를 느끼게 하는 것이었습니다. 뽑기로 얻은 장비는 한 번에 버려지지 않고 옵션 락과 리롤을 통해 원하는 방향으로 다듬어 갈 수 있도록 만들었으며, 한 런 안에서는 레벨업마다 9종의 패시브 중 무작위로 추천된 셋 중 하나를 골라 그 판만의 빌드 방향을 새로 정해 나가게 됩니다. 여기에 인게임에서도 마나석 조각을 모아 스킬을 직접 제작하거나 교체할 수 있도록 설계해, 한 판이 끝나기 전이라도 상황에 맞춰 스킬 구성 자체를 능동적으로 바꿔 나갈 수 있게 했습니다.",
    links: { git: "https://github.com/kjh7568/2D_project", video: "https://www.youtube.com/watch?v=FbooNqqnYjU", doc: "#" },
    titleImg: "assets/Hive Survivor_title.png",
    tags: ["Unity", "C#", "인터페이스 기반 설계", "JSON 데이터 드리븐", "Object Pooling", "Coroutine", "SpriteRenderer / Animator", "uGUI", "Tilemap"],
    features: [
      { title: "내가 쓸 장비를 키우는 재미", body: "한 번 뽑은 장비도 그대로 두지 않고 손을 댑니다. 마음에 드는 옵션은 락으로 보존하고 나머지만 마나석으로 다시 굴리는 흐름이라, '한 번만 더 뽑아볼까'의 작은 도박이 자연스럽게 이어집니다.", img: "assets/HiveSurvivor_feature_1.gif" },
      { title: "매 판 다시 짜는 빌드", body: "같은 캐릭터로 시작해도 매 판마다 빌드의 결이 달라집니다. 레벨업이 올라올 때마다 9종의 패시브 중 셋이 추천되고, 그중 하나를 골라 빌드의 방향을 새로 정합니니다.", img: "assets/HiveSurvivor_feature_2.png" },
      { title: "한 판 안에서 진화하는 빌드", body: "한 런이 끝날 때까지 스킬에 묶여 있지 않습니다. 적을 잡으며 모은 마나석 조각으로 인게임 중에도 스킬을 직접 만들고 갈아 끼울 수 있습니다.", img: "assets/HiveSurvivor_feature_3.gif" },
    ],
  },
  {
    id: "02",
    name: "Legend of Gem",
    tagline: "메인 젬과 보조 젬의 조합으로 자신만의 스킬을 만들어가는 3D 핵앤슬래시 액션 RPG",
    genre: "3D 핵앤슬래시 액션 RPG",
    duration: "2025.04.14 ~ 2025.04.30\n(16일)",
    period: "2025",
    team: "1인 (단독 개발)",
    role: "클라이언트",
    engine: "Unity 22.3.16f1 LTS\nJetBrains Rider\nGitHub Desktop",
    platform: "PC",
    intent: "이 프로젝트의 목표는 플레이어가 스킬은 '주어진 것'이 아닌 '직접 설계하는 것'으로 느끼게 하는 것이었습니다. 메인 젬을 슬롯에 끼워 스킬을 만들고 보조 젬을 추가로 조합해 동작 방식을 실시간으로 바꾸는 구조를 통해, '내가 만든 빌드로 던전을 돌파하는 재미'를 만들고자 했습니다. 여기에 드랍 시점마다 옵션이 새로 결정되는 장비 시스템을 더해, 더 좋은 빌드를 완성하려는 반복 사냥 동기가 자연스럽게 이어지도록 설계했습니다.",
    links: { git: "https://github.com/kjh7568/3D_Project", video: "https://www.youtube.com/watch?v=SoBuGS457F0", doc: "#" },
    titleImg: "assets/Legend of Gem_title.png",
    tags: ["Unity", "C#", "URP", "NavMesh", "ScriptableObject", "CSV 데이터 드리븐", "uGUI 드래그&드롭"],
    features: [
      { title: "내가 쓸 스킬을 직접 만든다", body: "메인 젬을 슬롯에 끼우는 순간 스킬이 생성됩니다. 보조 젬을 추가로 조합하면 동작 방식이 실시간으로 바뀌어, 같은 화염구라도 퍼지거나 빠르게 날아가거나 폭발 범위가 넓어지는 전혀 다른 스킬이 됩니다.", img: "assets/LegendofGem_feature_1.png" },
      { title: "똑같은 갑옷은 없다", body: "드랍되는 장비는 집어들 때마다 옵션이 새로 결정됩니다. 같은 부위의 갑옷이라도 레어도와 옵션 조합이 매번 달라, 더 좋은 빌드를 완성하려는 사냥 동기가 자연스럽게 이어집니다.", img: "assets/LegendofGem_feature_2.png" },
      { title: "무리를 쓸어버리는 카타르시스", body: "몬스터는 혼자가 아닌 3~5마리 단위 무리로 등장합니다. 보조 젬으로 강화한 광역 스킬 한 번이 무리를 한꺼번에 쓸어버리는 순간, 압박이 카타르시스로 바뀝니다.", img: "assets/LegendofGem_feature_3.png" },
    ],
  },
  {
    id: "03",
    name: "BANG! Online",
    tagline: "온라인 서부 카드 배틀 — 보드게임 BANG!의 멀티플레이 디지털 구현",
    genre: "온라인 멀티플레이 보드게임",
    duration: "2025.05.21 ~ 2025.05.29\n(9일)",
    period: "2025",
    team: "4인 팀",
    role: "클라이언트 + 네트워크",
    engine: "Unity 2022.3.16f1 LTS\nJetBrains Rider\nGitHub Desktop",
    platform: "PC",
    intent: "이 프로젝트의 목표는 보드게임 BANG!의 핵심인 '누구도 상대의 패를 모르는 심리전'을 온라인에서 그대로 살려내는 것이었습니다. 게임이 시작되면 보안관·무법자·배신자 역할이 비밀리에 배정되어, 같은 테이블에 앉은 플레이어 중 누가 내 편이고 누가 적인지 알 수 없는 상태에서 매 턴마다 카드 한 장을 두고 판단을 내려야 합니다. 원작의 룰을 충실히 구현하면서, 오프라인 보드게임 특유의 긴장감과 의심의 재미를 온라인 멀티플레이로 이식하는 것이 이 프로젝트의 출발점이었습니다.",
    links: { git: "https://github.com/kjh7568/Bang", video: "https://www.youtube.com/watch?v=sMGnw4uveAE", doc: "#" },
    titleImg: "assets/BangOnline_title.png",
    tags: ["Unity", "Photon Fusion", "Firebase Auth", "Firebase Firestore", "ScriptableObject", "RPC", "DOTween"],
    features: [
      { title: "방 코드 하나로 같은 테이블에", body: "방을 직접 만들거나 번호를 입력해 참가하면 됩니다. 닉네임이 실시간으로 동기화되며, 원하는 멤버가 모두 모이는 순간 바로 게임을 시작할 수 있습니다.", img: "assets/BangOnline_feature_1.png" },
      { title: "아무도 모르는 내 역할", body: "게임이 시작되는 순간 보안관·무법자·배신자 역할이 나에게만 보이게 배정됩니다. 같은 테이블 위에서 누가 내 편이고 누가 적인지 알 수 없는 채로 매 턴이 시작되며, 상대의 행동 하나하나가 단서가 됩니다.", img: "assets/BangOnline_feature_2.png" },
      { title: "누구를 쏠지가 곧 전략이다", body: "뱅! 카드를 사용하면 테이블 위 플레이어 중 원하는 한 명을 골라 직접 공격할 수 있습니다. 상대는 빗나감 카드로 막을지 피해를 감수할지 정할 수 있습니다.", img: "assets/BangOnline_feature_3.gif" },
    ],
  },
  {
    id: "04",
    name: "Augment Zero",
    tagline: "무기를 키우고 좀비를 쓸어라 — 하이퍼 FPS 로그라이크",
    genre: "FPS / 로그라이크",
    duration: "2025.06.07 ~ 2025.06.27\n(21일)",
    period: "2025",
    team: "2인 팀",
    role: "클라이언트",
    engine: "Unity 2022.3.16f1 LTS\nJetBrains Rider\nGitHub Desktop",
    platform: "PC",
    intent: "이 프로젝트의 목표는 전투의 결과가 즉각적인 성장으로 이어져 플레이어를 다음 웨이브로 이끄는 보상 루프를 만드는 것이었습니다. 몬스터를 처치해 얻은 코인으로 무기를 Common에서 Legendary까지 키워가는 성장감과, 웨이브를 클리어할 때마다 랜덤으로 제시되는 증강(Augment) 중 하나를 골라 빌드를 쌓아가는 선택의 재미를 함께 담았습니다. 매 판마다 다른 증강 조합과 무기 성장 경로가 펼쳐지고, 그 끝에 단 하나의 보스와 마주하는 긴장감 있는 클라이맥스를 목표로 설계했습니다.",
    links: { git: "https://github.com/kjh7568/FPS_Hyper_shooting", video: "https://www.youtube.com/watch?v=EWJNksDXTyU", doc: "#" },
    titleImg: "assets/AugmentZero_title.png",
    tags: ["Unity", "C#", "URP", "NavMesh", "StateMachine", "ScriptableObject"],
    features: [
      { title: "상황에 맞게 무기를 선택한다", body: "소총·권총·샷건·SMG·스나이퍼·나이프·수류탄, 7종의 무기를 전투 상황에 맞게 골라 전환할 수 있습니다. 원거리 저격과 근접 난전, 광역 제압까지 전투 성향을 정하는 것은 플레이어의 몫입니다.", img: "assets/AugmentZero_feature_1.gif" },
      { title: "내가 키운 무기가 더 강해진다", body: "몬스터를 처치해 얻은 코인을 상점에 투자하면 무기가 레벨업하고, Common에서 Legendary까지 등급이 오릅니다. 전투의 결과가 무기의 성장으로 이어지는 흐름이 다음 웨이브를 향한 동기가 됩니다.", img: "assets/AugmentZero_feature_2.gif" },
      { title: "패턴을 읽어야 이긴다", body: "최종 보스 Nasty는 이동·공격·스매시·기절·사망 5가지 상태를 전황에 따라 전환하며 행동합니다. 패턴을 읽고 대응하는 집중된 보스전이 매 런의 마지막에 기다리고 있습니다.", img: "assets/AugmentZero_feature_3.gif" },
    ],
  },
  {
    id: "05",
    name: "유니모",
    tagline: "몬스터를 피해 재화를 모아 나만의 별나무를 키우자!",
    genre: "모바일 캐주얼 수집·육성",
    duration: "2025.07.02 ~ 2025.08.08\n(37일)",
    period: "2025",
    team: "9인 팀 (개발 4, 기획 5)",
    role: "클라이언트",
    engine: "Unity 2022.3.16f1 LTS\nJetBrains Rider\nSourcetree",
    titleImg: "assets/Unimo_title.png",
    platform: "Android / iOS",
    intent: "이 프로젝트는 기업 협약으로 진행된 산학 협업으로, 파트너사 게임의 콘텐츠를 더 재미있게 개선하는 것이 팀의 공통 목표였습니다. 기획 파트가 방향을 수립하면 개발 파트가 이를 구현하는 구조 아래, 담당 업무는 보스 몬스터 추가 및 공격 패턴 설계, 몬스터 종류 확장, 스폰 로직 재설계, 몬스터 행동 로직 최적화였습니다. 요구사항을 정확히 파악해 Abstract Factory·State Machine 등의 패턴으로 구조화하며, 팀 전체 통합 흐름 안에서 담당 시스템을 안정적으로 완성하는 데 집중했습니다.",
    links: { git: "https://github.com/harangji/Unimo-StarTree", video: "#", doc: "#" },
    tags: ["Unity", "URP", "State Machine", "Abstract Factory", "Event Queue", "Object Pooling"],
    features: [
      {
        title: "예측하고 반응하는 보스전",
        body: "보스는 4가지 공격 패턴을 쿨타임에 따라 전환합니다. 어떤 패턴이 올지 예측하며 피하는 순간이 전투의 긴장감을 만들고, 패턴을 읽어낼수록 클리어가 쉬워집니다.",
        img: "assets/Unimo_feature_1.png",
      },
      {
        title: "초반의 여유, 후반의 압박",
        body: "몬스터는 웨이브 타이밍에 따라 단계적으로 등장합니다. 처음엔 여유 있게 재화를 모을 수 있지만, 스테이지가 진행될수록 화면을 채우는 압박감이 커집니다.",
        img: "assets/Unimo_feature_2.png",
      },
      {
        title: "자연스럽게 이어지는 몬스터 행동",
        body: "등장 → 예비 동작 → 공격 → 퇴장으로 이어지는 상태 전환이 몬스터마다 자연스럽게 연결됩니다. 뚝뚝 끊기지 않는 행동 흐름이 전투에 생동감을 더합니다.",
        img: "assets/Unimo_feature_3.png",
      },
    ],
  },
  {
    id: "06",
    name: "Tavern Tales",
    tagline: "선술집에서 용병을 고용하고 의뢰를 수행하는 자동 전투 길드 시뮬레이션",
    genre: "길드 운영 시뮬레이션 /\n오토배틀러",
    duration: "2026.01.14 ~ 2026.03.27\n(73일)",
    period: "2026",
    team: "1인 (단독 개발)",
    role: "클라이언트",
    engine: "Unity 6.0.3f1\nJetBrains Rider\nFork",
    titleImg: "assets/TavernTales_title.png",
    platform: "Android",
    intent: "이 프로젝트의 목표는 플레이어가 용병을 단순한 전투 자원이 아닌 관리해야 할 동료로 느끼게 하는 것이었습니다. 역할군에 따라 탱커가 실제로 피해를 흡수하고 원딜이 뒤에서 공격하는 전략적 자동 전투를 구현해, 배치 편성이 그대로 결과로 이어지는 쾌감을 만들었습니다. 전투가 끝난 뒤 부상 상태가 다음 의뢰까지 지속되고, 사망한 용병은 부활 확인 없이 회복되지 않도록 설계함으로써 무리한 의뢰를 피하고 팀 상태를 살피며 선택을 내리는 길드 운영의 책임감을 플레이의 중심에 두었습니다.",
    links: { git: "https://github.com/kjh7568/Project_G", video: "#", doc: "#" },
    tags: ["Unity 6", "C#", "URP", "Android", "Auto-Battle", "Grid-based Combat", "Factory Pattern", "BFS 경로 탐색", "Dependency Injection", "Drag & Drop UI (uGUI)"],
    features: [
      {
        title: "탱커가 앞에서 맞아준다",
        body: "배치한 위치가 그대로 전투에서 살아납니다. 탱커는 적의 시선을 끌어 앞에서 버티고, 원거리 딜러는 뒤에서 안전하게 공격합니다. 편성을 짜는 것 자체가 전략이 되는 전투입니다.",
        img: "assets/TavernTales_feature_1.png",
      },
      {
        title: "마나를 채워 사용하는 스킬",
        body: "11명의 용병은 각자 다른 스킬을 가집니다. 전투를 거칠수록 마나가 차오르고, 가득 찼을 때 터지는 고유 스킬을 사용합니다. '저 용병 마나 다 찼다'라는 그 순간을 기대하며 전투를 지켜보게 됩니다.",
        img: "assets/TavernTales_feature_2.gif",
      },
      {
        title: "용병은 관리해야 할 동료다",
        body: "전투가 끝나도 부상은 남습니다. 체력이 많이 깎인 용병은 다음 의뢰에서 제 실력을 내지 못하고, 사망한 용병은 부활 확인 없이 돌아오지 않습니다. 무리하지 않고 팀 상태를 살피며 의뢰를 고르는 것이 길드 운영의 핵심이 됩니다.",
        img: "assets/TavernTales_feature_3.gif",
      },
    ],
  },
  {
    id: "07",
    name: "Clone Puzzle",
    tagline: "혼자서 둘이 되는 시간차 협력 퍼즐 플랫포머",
    genre: "퍼즐 플랫포머",
    duration: "2026.04.15 ~ 2026.04.27\n(13일)",
    period: "2026",
    team: "1인 (단독 개발)",
    role: "클라이언트",
    engine: "Unity 6 (6000.3.6f1)\nJetBrains Rider\nFork",
    titleImg: "assets/ClonePuzzle_title.png",
    platform: "모바일",
    intent: "이 프로젝트의 목표는 혼자서도 협력 퍼즐의 쾌감을 느낄 수 있는 경험을 만드는 것이었습니다. 플레이어의 행동이 프레임 단위로 녹화되어 클론으로 재생되는 구조를 통해, 과거의 내가 지금의 나를 돕는 시간차 협력을 구현했습니다. 저울·버튼·물체 들기 등 서로 다른 규칙의 기믹들을 스테이지마다 조합해 '이번엔 클론을 어떻게 써야 하지?'라는 발견을 반복하게 했고, 그 정답을 스스로 설계하는 과정에서 창작의 성취감이 남도록 의도했습니다.",
    links: { git: "https://github.com/kjh7568/Clone-Puzzle", video: "#", doc: "#" },
    tags: ["Unity 6", "URP 2D", "Physics2D", "DOTween", "ScriptableObject", "Interface-driven Architecture", "Unity Input System"],
    features: [
      {
        title: "내 행동이 클론이 된다",
        body: "한 번의 플레이가 그냥 끝나지 않습니다. 녹화된 행동이 클론으로 남아 다음 시도에 똑같이 재생됩니다. 혼자 시작했지만, 어느 순간 과거의 내가 지금의 나를 돕고 있습니다.",
        img: "assets/ClonePuzzle_feature_1.gif",
      },
      {
        title: "매 스테이지, 새로운 발견",
        body: "저울, 버튼, 물체 들기 — 기믹마다 규칙이 다릅니다. 스테이지가 바뀔 때마다 클론을 어떻게 활용해야 할지 다시 생각하게 됩니다. 새로운 조합을 발견하는 순간이 퍼즐의 재미입니다.",
        img: "assets/ClonePuzzle_feature_2.gif",
      },
      {
        title: "내가 직접 짜는 팀 전략",
        body: "클론이 버튼을 밟는 사이 플레이어가 이동하고, 클론이 저울을 누르는 동안 열린 길로 진행합니다. 정답은 주어지지 않습니다. 클론과 나의 행동 순서를 직접 설계할 때 성취감이 완성됩니다.",
        img: "assets/ClonePuzzle_feature_3.gif",
      },
    ],
  },
];

window.PROJECTS = PROJECTS;
